### ISSUE TITLE
Wayland metabug

### ISSUE THREAD

**Issue by vberger** [tomaka/winit#306]
There are several issues with wayland. Most of them come from the fact that wayland does things differently than other platforms. I open this issue to list know issues and hopefully get discussion going about them.

## The borders of my windows are not drawn the right size

This is perhaps the most regular issue, caused by several wayland particularities:

- wayland clients (with exception of KDE) are expected to draw their own borders. This is done by winit using [wayland-window](https://github.com/Smithay/wayland-window), this is why the borders are ugly and missing buttons, see https://github.com/smithay/wayland-window/issues if you want to help.
- The dimensions of a wayland window is defined by the dimensions of its contents (with glutin, the EGL surface).

This means that winit know about the size of borders but not of the contents. Meaning the user needs to keep the two in sync by calling `window.set_inner_size()` appropriately. Hopefully at some point glutin will be able to handle it directly.

## My app crashes at startup with a message about a surface not being configured

See https://docs.rs/winit/0.8.2/winit/os/unix/trait.WindowExt.html#tymethod.is_ready

Note that depending on the wayland environment, this issue can manifest itself differently

## Other issues 

To be completed

**Comment by jwilm** [comment]
Key repeat: https://github.com/jwilm/alacritty/issues/760

**Comment by vberger** [comment]
> Key repeat: jwilm/alacritty#760

For the record, this is something that needs to be implemented in winit. The wayland server won't do the repeat itself, it only sends use what are the delay and repeat frequency, and we are supposed to handle it ourselves.

Now the big question is: how to we generate this stream of events?

**Comment by jwilm** [comment]
Doesn't the server have some support for timers? Is that something that can be used by the client?

**Comment by vberger** [comment]
Well, `libwayland-server.so` does expose some timer API, but it is for internal use of the server only and not exposed by the protocol.

Though, it's just a light wrapper around a timerfd. The cleaner way I see currently to handle the repeating keys would be to use a timerfd ourselves, and hook it and the wayland event queue into a small mio event loop (which is perfectly possible, wayland does expose the required API).

**Comment by jwilm** [comment]
`hidpi_factor` should actually compute the scale factor rather than hardcode 1.0. Alacritty needs this to properly scale fonts for the user.

**Comment by vberger** [comment]
Good point. Let's move to #315 to figure out the details.

**Comment by newpavlov** [comment]
I am using Debian 9 with Gnome 3.22.3 on Wayland. When I launch example from `wayland-window` I am getting the following result:
<details>
  <summary>Click to expand</summary>

![1](https://user-images.githubusercontent.com/329626/31997631-5b756898-b995-11e7-8b4a-e3c3ffef9f01.png)

Also it does not get handled correctly in the overview mode (not sure how it's properly called):
![2](https://user-images.githubusercontent.com/329626/31997719-a4b314c4-b995-11e7-85b2-a0838a253480.png)

</details>

Also it looks like `with_dimensions`, `with_fullscreen` and `with_title` methods do not work at all. Not sure if it's `winit` problem or some bug on Debian side, but I thought it's worth to report it.

**Comment by vberger** [comment]
@newpavlov Ah, that's interesting.

Would you mind moving this to wayland-window's repository (as this is clearly a wayland-window issue) by opening an issue there, and providing with it the output of running this example with the `WAYLAND_DEBUG=1` environment variable?

**Comment by JustinRyanH** [comment]
Let me make sure I understand. These are the current known issues with Wayland and Winit
### Wayland Problems
- [ ] Touch Events are not supported
- [ ] Holding down a key does not perform Repeat Keys
- [ ] Drag & Drop/Copy & Paste Doesn't work
- [ ] HiDPI handling is un-implemented
- [ ] Cannot set the cursor

I am uncertain of what `Hide/Show the Window` and `Cursor Grabbing` covers.

**Comment by vberger** [comment]
`Hide/Show the window` refers to the [`Window::show`](https://docs.rs/winit/0.8.3/winit/struct.Window.html#method.show) and [`Window::hide`](https://docs.rs/winit/0.8.3/winit/struct.Window.html#method.hide) methods of winit, which currently have no effect on wayland.

`Curso Grabbing` is described in the [`CursorState::Grab`](https://docs.rs/winit/0.8.3/winit/enum.CursorState.html#variant.Grab)

**Comment by fooishbar** [comment]
> For the record, this is something that needs to be implemented in winit. The wayland server won't do the repeat itself, it only sends use what are the delay and repeat frequency, and we are supposed to handle it ourselves.
> 
> Now the big question is: how to we generate this stream of events?

You're right that wayland-server's timers won't help you. The only reason timers are there is because libwayland-server contains a lame event loop; they're not at all exposed over the protocol.

You'd have to hook a timer into the winit event loop and generate key events internally. Note that [xkb_keymap_key_repeats](https://xkbcommon.org/doc/current/group__components.html#ga9d7f998efeca98b3afc7c257bbac90a8) will tell you whether or not a particular key-down event should repeat or not.

**Comment by SethDusek** [comment]
Have you taken a look at [KDE's server side decoration protocol](https://github.com/swaywm/wlroots/blob/master/protocol/server-decoration.xml)? I belive that wlroots (and by extension sway) and KDE Plasma both support this, so this is a decent solution for now. I think it is not an official protocol in wayland-protocols yet, but GTK has support for it and so does QT.

I could attempt to add this to winit but I have no experience with wayland so I can't really help. It'd take me some time before I could be able to work on this

**Comment by vberger** [comment]
Yes, this is a known option.

Winit delegates the decoration-handling in wayland to [wayland-window](https://github.com/smithay/wayland-window), and my goal was to implement this fallback in wayland-window: https://github.com/Smithay/wayland-window/issues/25. It has just not been done yet, because I have a limited bandwidth...

**Comment by vberger** [comment]
For the record, I've implemented the server-side decoration protocol in SCTK, see https://github.com/Smithay/client-toolkit/pull/20, using the now "standard" xdg-decoration protocol.

I don't know if many wayland compositors already implement it, though.
